Fixed meetingitem_view.pt: PTRuntimeError: ['Compilation failed', u'zope.tal.taldefs.TALError: TAL attributes on <tal:displaybudgetinfos> require explicit </tal:displaybudgetinfos>, at line 464, column 9']